# Generated by Django 4.0.3 on 2022-05-08 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name1', models.CharField(max_length=255)),
                ('email1', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=13)),
                ('describe', models.TextField()),
            ],
        ),
    ]
